version: '3'
services:
  tools-debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
      args:
        - KUBECTL_VERSION=1.20.5
        - KUSTOMIZE_VERSION=3.10.0
        - CROSSPLANE_VERSION=1.1.0
    image: quay.io/matteojoliveau/k8s-tools:1.20.5-buster
  tools-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        - KUBECTL_VERSION=1.20.5
        - KUSTOMIZE_VERSION=3.10.0
        - CROSSPLANE_VERSION=1.1.0
    image: quay.io/matteojoliveau/k8s-tools:1.20.5-alpine
