version: '3'
services:
  tools-debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
      args:
        - KUBECTL_VERSION=1.21.1
        - KUSTOMIZE_VERSION=4.1.3
        - CROSSPLANE_VERSION=1.2.1
        - HELM_VERSION=3.5.4
        - YQ_VERSION=4.9.3
    image: quay.io/matteojoliveau/k8s-tools:1.21.1-buster
  tools-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        - KUBECTL_VERSION=1.21.1
        - KUSTOMIZE_VERSION=4.1.3
        - CROSSPLANE_VERSION=1.2.1
        - HELM_VERSION=3.5.4
        - YQ_VERSION=4.9.3
    image: quay.io/matteojoliveau/k8s-tools:1.21.1-alpine
