version: '3'
services:
  tools-debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
      args:
        - KUBECTL_VERSION=1.20.2
        - KUSTOMIZE_VERSION=3.10.0
    image: quay.io/matteojoliveau/k8s-tools:1.20.2-stretch
  tools-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        - KUBECTL_VERSION=1.20.2
        - KUSTOMIZE_VERSION=3.10.0
    image: quay.io/matteojoliveau/k8s-tools:1.20.2-alpine
