version: '3'
services:
  tools-debian:
    build:
      context: .
      dockerfile: Dockerfile.debian
      args:
        - KUBECTL_VERSION=1.19.4
        - KUSTOMIZE_VERSION=3.8.7
    image: quay.io/matteojoliveau/k8s-tools:1.19.4-stretch
  tools-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        - KUBECTL_VERSION=1.19.4
        - KUSTOMIZE_VERSION=3.8.7
    image: quay.io/matteojoliveau/k8s-tools:1.19.4-alpine
