version: 2
jobs:
  alpine:
    docker:
      - image: docker:stable
        environment:
          - KUBECTL_VERSION_URL: https://storage.googleapis.com/kubernetes-release/release/stable.txt
          - KUSTOMIZE_VERSION: 3.2.0
          - SKAFFOLD_VERSION: 0.38.0
          - DOCKER_IMAGE: matteojoliveau/k8s-tools

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Fetch kubectl stable version
          command: |
            apk update
            apk add curl
            export KUBECTL_VERSION=$(curl $KUBECTL_VERSION_URL | sed 's/v//')

      - run:
          name: Login with Docker Hub
          command: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_TOKEN
          
      - run:
          name: Build images
          command: |
            docker build -t $DOCKER_IMAGE:$KUBECTL_VERSION-alpine -f Dockerfile.alpine .
            docker tag $DOCKER_IMAGE:$KUBECTL_VERSION-alpine $DOCKER_IMAGE:alpine
            docker tag $DOCKER_IMAGE:$KUBECTL_VERSION-alpine $DOCKER_IMAGE:latest
            docker push $DOCKER_IMAGE:$KUBECTL_VERSION-alpine
            docker push $DOCKER_IMAGE:alpine
            docker push $DOCKER_IMAGE:latest
  alpine:
    docker:
      - image: docker:stable
        environment:
          - KUBECTL_VERSION_URL: https://storage.googleapis.com/kubernetes-release/release/stable.txt
          - KUSTOMIZE_VERSION: 3.2.0
          - SKAFFOLD_VERSION: 0.38.0
          - DOCKER_IMAGE: matteojoliveau/k8s-tools

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Fetch kubectl stable version
          command: |
          apk update
          apk add curl
          export KUBECTL_VERSION=$(curl $KUBECTL_VERSION_URL | sed 's/v//')

      - run:
          name: Login with Docker Hub
          command: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_TOKEN

      - run:
          name: Build images
          command: |
            docker build -t $DOCKER_IMAGE:$KUBECTL_VERSION-debian -f Dockerfile.debian .
            docker tag $DOCKER_IMAGE:$KUBECTL_VERSION-debian $DOCKER_IMAGE:debian
            docker push $DOCKER_IMAGE:$KUBECTL_VERSION-debian
            docker push $DOCKER_IMAGE:debian
      
workflows:
  version: 2
  build_and_push:
    jobs:
      - alpine:
          filters:
            branches:
              only:
                - master

      - debian:
          filters:
            branches:
              only:
                - develop
                - master
          