name: Debian image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Quay
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin quay.io
      - name: Build the Docker image
        env:
          KUBECTL_VERSION: 1.19.4
          KUSTOMIZE_VERSION: 3.9.0
        run: |
          docker build \
            --file Dockerfile.debian \
            --tag quay.io/matteojoliveau/k8s-tools:$KUBECTL_VERSION-debian \
            --tag quay.io/matteojoliveau/k8s-tools:debian \
            --tag quay.io/matteojoliveau/k8s-tools:latest \
            --build-arg KUBECTL_VERSION=$KUBECTL_VERSION \
            --build-arg KUSTOMIZE_VERSION=$KUSTOMIZE_VERSION \
            .
          docker push quay.io/matteojoliveau/k8s-tools:$KUBECTL_VERSION-debian
