name: Debian image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Quay
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin quay.io
      - name: Build the Docker image
        env:
          KUBECTL_VERSION: 1.21.1
          KUSTOMIZE_VERSION: 4.1.3
          CROSSPLANE_VERSION: 1.2.1
          HELM_VERSION: 3.5.4
          YQ_VERSION: 4.9.3
        run: |
          docker build \
            --file Dockerfile.debian \
            --tag quay.io/matteojoliveau/k8s-tools:$KUBECTL_VERSION-debian \
            --tag quay.io/matteojoliveau/k8s-tools:debian \
            --tag quay.io/matteojoliveau/k8s-tools:latest \
            --build-arg KUBECTL_VERSION=$KUBECTL_VERSION \
            --build-arg KUSTOMIZE_VERSION=$KUSTOMIZE_VERSION \
            --build-arg CROSSPLANE_VERSION=$CROSSPLANE_VERSION \
            --build-arg HELM_VERSION=$HELM_VERSION \
            --build-arg YQ_VERSION=$YQ_VERSION \
            .
          docker push quay.io/matteojoliveau/k8s-tools:$KUBECTL_VERSION-debian
